-- 관리자 알림 읽음 처리 테이블
CREATE TABLE ADMIN_NOTIFICATION_READ (
    ADMIN_ID VARCHAR2(50) NOT NULL,
    TYPE VARCHAR2(20) NOT NULL, -- 'inquiry', 'order', 'report'
    LAST_READ_TIME DATE NOT NULL,
    CONSTRAINT PK_ADMIN_NOTIFICATION_READ PRIMARY KEY (ADMIN_ID, TYPE)
);

COMMENT ON TABLE ADMIN_NOTIFICATION_READ IS '관리자 알림 읽음 처리';
COMMENT ON COLUMN ADMIN_NOTIFICATION_READ.ADMIN_ID IS '관리자 ID';
COMMENT ON COLUMN ADMIN_NOTIFICATION_READ.TYPE IS '알림 타입 (inquiry, order, report)';
COMMENT ON COLUMN ADMIN_NOTIFICATION_READ.LAST_READ_TIME IS '마지막 읽음 시간';

