-- 관리자 활동 로그 테이블 생성
CREATE TABLE ADMIN_ACTIVITY_LOG (
    LOG_NO NUMBER PRIMARY KEY,
    ADMIN_ID VARCHAR2(30) NOT NULL,
    ACTION_TYPE VARCHAR2(50) NOT NULL, -- 'ORDER_UPDATE', 'INQUIRY_ANSWER', 'BOARD_DELETE', 'USER_DELETE', 'BANNER_UPDATE' 등
    ACTION_DESCRIPTION VARCHAR2(500), -- 상세 설명
    TARGET_ID VARCHAR2(50), -- 대상 ID (주문번호, 문의번호, 게시물번호 등)
    TARGET_TYPE VARCHAR2(50), -- 대상 타입 ('ORDER', 'INQUIRY', 'BOARD', 'USER' 등)
    IP_ADDRESS VARCHAR2(50),
    CDATE DATE DEFAULT SYSDATE
);

-- 시퀀스 생성
CREATE SEQUENCE ADMIN_ACTIVITY_LOG_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 인덱스 생성 (조회 성능 향상)
CREATE INDEX IDX_ADMIN_ACTIVITY_LOG_ADMIN_ID ON ADMIN_ACTIVITY_LOG(ADMIN_ID);
CREATE INDEX IDX_ADMIN_ACTIVITY_LOG_CDATE ON ADMIN_ACTIVITY_LOG(CDATE);
CREATE INDEX IDX_ADMIN_ACTIVITY_LOG_ACTION_TYPE ON ADMIN_ACTIVITY_LOG(ACTION_TYPE);

